### ISSUE TITLE
are those charts published somewhere?

### ISSUE THREAD

**Issue by kostyrev** [articulate/helmcharts#3]
I mean helm repository

**Comment by hetii** [comment]
Probably not, but if you install [helm-git](https://github.com/aslafy-z/helm-git) you can use this repository directly.

Example:

    helm repo add articulate "git+https://github.com/articulate/helmcharts@stable"
    helm upgrade --install pritunl articulate/pritunl -n pritunl -f pritunl-values.yaml

**Comment by echoboomer** [comment]
The chart binaries are not published anywhere. There is a PR I've opened to make some updates if the maintainers get around to approving it. I will also push the latest version of that binary somewhere public.

**Comment by echoboomer** [comment]
@kostyrev @hetii I have republished the latest version of this chart with some improvements: https://github.com/shipwreckdev/charts/tree/master/stable/pritunl

A binary of the chart is included in that repository, but I realize this is not as useful as having a public repo to pull them from. This will at least assist as a temporary measure.
